# Generated by Django 4.1.1 on 2022-09-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('0', 'TASKLIST'), ('1', 'CALENDAR'), ('2', 'CARDGALERY'), ('3', 'LIST'), ('4', 'NOTES')], max_length=1)),
                ('text', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('0', 'TODO'), ('1', 'DONE')], default='TODO', max_length=1)),
                ('supgaes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subpages.subpages')),
            ],
        ),
    ]
