# Generated by Django 4.1.1 on 2022-09-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='supgaes_id',
            new_name='subpages',
        ),
    ]
