# Generated by Django 4.1.1 on 2022-09-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subpages', '0003_alter_subpages_pages'),
        ('Tasks', '0002_rename_supgaes_id_tasks_subpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subpages',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Subpages.subpages'),
        ),
    ]
