# Generated by Django 4.1.1 on 2022-10-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_tasks_subpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('0', 'TODO'), ('1', 'DONE')], default='TODO', max_length=4),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('0', 'TASKLIST'), ('1', 'CALENDAR'), ('2', 'CARDGALERY'), ('3', 'LIST'), ('4', 'NOTES')], max_length=10),
        ),
    ]
