# Generated by Django 4.1.1 on 2022-09-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('big_image', models.CharField(max_length=100)),
                ('small_image', models.CharField(max_length=100)),
                ('pages_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.pages')),
            ],
        ),
    ]
