# Generated by Django 4.1.1 on 2022-09-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_remove_pages_tat_id'),
        ('Subpages', '0003_alter_subpages_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpages',
            name='pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.pages'),
        ),
    ]
