# Generated by Django 4.1.1 on 2022-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subpages', '0004_alter_subpages_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpages',
            name='big_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subpages',
            name='small_image',
            field=models.CharField(max_length=500),
        ),
    ]
