# Generated by Django 4.1.1 on 2022-09-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_alter_pages_tat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='tat_id',
            field=models.CharField(max_length=100),
        ),
    ]
