# Generated by Django 4.1.1 on 2022-09-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_alter_pages_tat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='tat_id',
        ),
    ]
